controllers/GameController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Games;
use app\models\Comments;
use app\models\GameSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\filters\AccessControl;

/**
 * GameController implements the CRUD actions for Games model.
 */
class GameController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true, // Has access
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index', 'view', 'getcomment'],
                        'allow' => true, // Do not have access
                        'roles'=>['?'], // Guests '?'
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Games models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GameSearch();
        $params = Yii::$app->request->queryParams;
        if (isset($params["search_query"])){
            $searchModel->search_query = $params["search_query"];
        }
        if (isset($params["order_by"])){
            $searchModel->order_by = $params["order_by"];
        }

        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Games model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Games model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Games();
        $model->setscenario('insert');

        if ($model->load(Yii::$app->request->post())) {
            $model->AuthorId = Yii::$app->user->identity->UserId;
            $model->PostDate = new \yii\db\Expression('NOW()');

            $file1 = UploadedFile::getInstance($model, 'file');
            $model->file = $file1;

            date_default_timezone_set('Asia/Jakarta');
            
            $model->Image = 'img_'.date('dMY').'_'.date('His').'.'.$file1->extension;

                
            if ($model->save()){
                $model->file->saveAs('img/' . $model->Image); 

                return $this->redirect(['view', 'id' => $model->GameId]);   
            }else{
                return $this->render('create', [
                    'model' => $model,
                ]);    
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Games model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            date_default_timezone_set('Asia/Jakarta');

            $file1 = UploadedFile::getInstance($model, 'file');
            if ($file1 == null && $model->Image == ""){
                $model->addError('file', 'Please upload a file.');
                return $this->render('update', [
                    'model' => $model,
                ]);
            }

            if ($file1 != null){  
                $model->Image = 'img_'.date('dmY').'_'.date('His').'.'.$file1->extension;
                $model->file = $file1;
            }

            if ($model->save()){
                if ($file1 != null){
                    $model->file->saveAs('img/' . $model->Image);
                }
                return $this->redirect(['view', 'id' => $model->GameId]);   
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Games model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Games model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Games the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Games::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPostcomment()
    {
        $isAjax = isset($_SERVER['HTTP_X_REQUESTED_WITH']) AND 
            strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest';
        
        if (!$isAjax)
            throw new NotFoundHttpException('The requested page does not exist.');

        date_default_timezone_set('Asia/Jakarta');

        if (isset($_POST["game"]) && isset($_POST["comment"])){
            $model = new Comments();
            $model->GameId = $_POST["game"];
            $model->AuthorId = Yii::$app->user->identity->UserId;
            $model->Comment = $_POST["comment"];
            $model->PostDate = new \yii\db\Expression('NOW()');

            $model->save();

            $model = Comments::findOne($model->CommentId);

            return json_encode([
                'comment' => $model->Comment, 
                'id' => $model->CommentId, 
                'author' => $model->author->Firstname.' '.$model->author->Lastname, 
                'date' => $this->dateFormat($model->PostDate),
                'image' => $model->author->Image == null || $model->author->Image == "" ? 'default-pp.jpg' : $model->author->Image
            ]);
        }else{
            return [];
        }
    }

    public function actionGetcomment()
    {
        date_default_timezone_set('Asia/Jakarta');

        $isAjax = isset($_SERVER['HTTP_X_REQUESTED_WITH']) AND 
            strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest';
        
        if (!$isAjax || !isset($_GET['game']))
            throw new NotFoundHttpException('The requested page does not exist.');

        $model = new Comments();

        if (isset($_GET['id']) && $_GET['id'] > 0){
            $model = Comments::find()
                ->where('CommentId < :id', [':id' => $_GET['id']])
                ->andWhere('GameId = :game', [':game' => $_GET['game']])
                ->orderBy([ 'Postdate' => SORT_DESC ])
                ->limit(5)->all();
        }else{
            $model = Comments::find()
                ->where('GameId = :game', [':game' => $_GET['game']])
                ->orderBy([ 'Postdate' => SORT_DESC ])
                ->limit(5)
                ->all();   
        }

        $output = [];
        $minid = -1;

        foreach($model as $row){
            if ($minid == -1 || $minid > $row->CommentId){
                $minid = $row->CommentId;
            }
        }

        $comment_count = Comments::find()
            ->where('CommentId < :id', [':id' => $minid])
            ->andWhere('GameId = :game', [':game' => $_GET['game']])
            ->count();

        foreach($model as $row){
            array_push($output, [
                'comment' => $row->Comment, 
                'count' => $comment_count, 
                'id' => $row->CommentId, 
                'author' => $row->author->Firstname.' '.$row->author->Lastname, 
                'date' => $this->dateFormat($row->PostDate),
                'image' => $row->author->Image == null || $row->author->Image == "" ? 'default-pp.jpg' : $row->author->Image
            ]);
        }

        return json_encode($output);
    }

    function dateFormat($date){
        date_default_timezone_set('Asia/Jakarta');

        if (date('dmY') == date("dmY", strtotime($date))){
            return date("h:i A", strtotime($date)). ' Today';
        }else if (date('dmY') == date("dmY", strtotime('+1 day', strtotime($date)))){
            return date("h:i A", strtotime($date)). ' Yesterday';
        }else{
            return date("h:i A M d, Y", strtotime($date));
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Users;
use app\models\LoginForm;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\GameSearch;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for Users model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['register'],
                        'allow' => false, // Has access
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true, // Has access
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['register'],
                        'allow' => true, // Do not have access
                        'roles'=>['?'], // Guests '?'
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionRegister()
    {
        //Yii::$app->user->identity
        $model = new Users();
        $model->setscenario('insert');

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            date_default_timezone_set('Asia/Jakarta');

            $file1 = UploadedFile::getInstance($model, 'file');
            if ($file1 != null){  
                $model->Image = 'img_'.date('dmY').'_'.date('His').'.'.$file1->extension;
                $model->file = $file1;
            }

            $model->DateOfBirth = date("Y-m-d", strtotime($model->DateOfBirth));
            if ($model->Password != $model->varPassword){
                //reset password
                $model->Password = "";
                $model->varPassword = "";

                //set error message
                $model->addError('varPassword', 'Password confirm must be the same as password');
                $model->DateOfBirth = date("d-M-Y", strtotime($model->DateOfBirth));
                $model->file = null;

                return $this->render('register', [
                    'model' => $model,
                ]);
            }

            $model->Password = crypt($model->Password);

            if ($model->save()){

                if ($file1 != null){
                    $model->file->saveAs('img/' . $model->Image);
                }

                Yii::$app->user->login($model, 0);
                return $this->redirect(['site/index']);
                
            }else{
                $model->file = null;
                $model->DateOfBirth = date("d-M-Y", strtotime($model->DateOfBirth));
                return $this->render('register', [
                    'model' => $model,
                ]);   
            }
        } else {
            $model->file = null;
            return $this->render('register', [
                'model' => $model,
            ]);
        }
    }

    public function actionProfile()
    {
        $id = Yii::$app->user->identity->UserId;
        $model = $this->findModel($id);

        $searchModel = new GameSearch();
        $params = Yii::$app->request->queryParams;
        if (isset($params["search_query"])){
            $searchModel->search_query = $params["search_query"];
        }
        if (isset($params["order_by"])){
            $searchModel->order_by = $params["order_by"];
        }

        $searchModel->owner = $id;

        $dataProvider = $searchModel->search($params);

        return $this->render('profile', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate()
    {
        $id = Yii::$app->user->identity->UserId;
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            date_default_timezone_set('Asia/Jakarta');

            $file1 = UploadedFile::getInstance($model, 'file');
            if ($file1 != null){  
                $model->Image = 'img_'.date('dmY').'_'.date('His').'.'.$file1->extension;
                $model->file = $file1;
            }

            $model->DateOfBirth = date("Y-m-d", strtotime($model->DateOfBirth));

            if ($model->save()){
                if ($file1 != null){
                    $model->file->saveAs('img/' . $model->Image);
                }

                return $this->redirect(['profile']);   
            }else{
                $model->DateOfBirth = date("d-M-Y", strtotime($model->DateOfBirth));
                $model->file = null;
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        } else {
            $model->file = null;
            $model->DateOfBirth = date("d-M-Y", strtotime($model->DateOfBirth));
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionChangepassword()
    {
        $id = Yii::$app->user->identity->UserId;
        $model = $this->findModel($id);
        $model->setscenario('change');

        if ($model->load(Yii::$app->request->post())) {
            if (!$model->validatePassword($model->curPassword)){
                $model->curPassword = "";
                $model->varPassword = "";
                $model->newPassword = "";
                $model->addError('curPassword', 'Your current Password is incorrect');
                return $this->render('changepassword', [
                    'model' => $model,
                ]);
            }

            if ($model->newPassword != $model->varPassword){
                $model->curPassword = "";
                $model->varPassword = "";
                $model->newPassword = "";
                $model->addError('varPassword', 'Password confirm must be the same as new password');
                return $this->render('changepassword', [
                    'model' => $model,
                ]);
            }

            $model->Password = crypt($model->newPassword);

            if ($model->save()){
                return $this->redirect(['profile']);
            }

        } else {
            return $this->render('changepassword', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
    <link rel="stylesheet" href="<?= \Yii::$app->request->BaseUrl; ?>/dist/css/skins/skin-blue.min.css">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="<?= \Yii::$app->request->BaseUrl; ?>/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="<?= \Yii::$app->request->BaseUrl; ?>/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="<?= \Yii::$app->request->BaseUrl; ?>/ionicons-2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="<?= \Yii::$app->request->BaseUrl; ?>/dist/css/AdminLTE.min.css">
</head>
<body class="skin-blue layout-top-nav">
<?php $this->beginBody() ?>

<div class="wrapper">
    <header class="main-header">

        <nav class="navbar navbar-static-top" role="navigation">
        
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#w0-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= \Yii::$app->request->BaseUrl; ?>">Fundnel Tech</a>
        </div>
        
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              
              <!-- Tasks Menu -->
<?php if (!Yii::$app->user->isGuest) { ?>
              <li><?= Html::a('<i class="fa fa-plus-circle"></i> New Game', ['/game/create']) ?></li>
<?php } ?>
              <li><?= Html::a('Home', ['/site/index']) ?></li>
              <li><?= Html::a('Games', ['/game/index']) ?></li>
<?php if (Yii::$app->user->isGuest) { ?>
              <li><?= Html::a('Register', ['/user/register']) ?></li>
              <li><?= Html::a('Login', ['/site/login']) ?></li>
<?php } ?>
<?php if (!Yii::$app->user->isGuest) { ?>
              <li><?= Html::a('My Pages', ['/user/profile']) ?></li>
              <!-- User Account Menu -->
              <li class="dropdown user user-menu">
                <!-- Menu Toggle Button -->
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <!-- The user image in the navbar-->
                  <img src="<?= \Yii::$app->request->BaseUrl; ?>/img/<?= Yii::$app->user->identity->Image == null || Yii::$app->user->identity->Image == "" ? 'default-pp.jpg' : Yii::$app->user->identity->Image ?>" class="user-image" alt="User Image">
                  <!-- hidden-xs hides the username on small devices so only the image appears. -->
                  <span class="hidden-xs"><?= Yii::$app->user->identity->Firstname . ' ' . Yii::$app->user->identity->Lastname ?></span>
                </a>
                <ul class="dropdown-menu">
                  <!-- The user image in the menu -->
                  <li class="user-header">
                    <img src="<?= \Yii::$app->request->BaseUrl; ?>/img/<?= Yii::$app->user->identity->Image == null || Yii::$app->user->identity->Image == "" ? 'default-pp.jpg' : Yii::$app->user->identity->Image ?>" class="img-circle" alt="User Image">
                    <p>
                      <?= Yii::$app->user->identity->Firstname . ' ' . Yii::$app->user->identity->Lastname ?>
                      <small><?= Yii::$app->user->identity->Email ?></small>
                    </p>
                  </li>
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <?= Html::a('Change password', ['/user/changepassword'], ['class'=>'btn btn-default btn-flat']) ?>
                    </div>
                    <div class="pull-right">
                      <?= Html::a('Sign out', ['/site/logout'],['data-method' => 'post','class'=>'btn btn-default btn-flat']) ?>
                    </div>
                  </li>
                </ul>
              </li>
<?php } ?>
              
            </ul>
          </div>
        </nav>
    </header>
    <div class="content-wrapper">
        <div class="container">
            <section class="content-header">
                <h1><?= $this->title ?></h1>
                <?= Breadcrumbs::widget([
                    'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
                ]) ?>
            </section>
            <section class="content">
            <?= $content ?>
                
            </section>
        </div>
    </div>

    <footer class="main-footer">
        <div class="container">
            <div class="pull-right hidden-xs">
                <b>Version</b> 2.3.0
            </div>
            <strong>Copyright © 2014-2015 <a href="http://almsaeedstudio.com">Almsaeed Studio</a>.</strong> All rights reserved.
        </div><!-- /.container -->
    </footer>
</div>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

<!-- jQuery 2.1.4 -->
<!--<script src="<?= \Yii::$app->request->BaseUrl; ?>/plugins/jQuery/jQuery-2.1.4.min.js"></script>-->
<!-- Bootstrap 3.3.5 -->
<script src="<?= \Yii::$app->request->BaseUrl; ?>/bootstrap/js/bootstrap.min.js"></script>
<!-- AdminLTE App -->
<script src="<?= \Yii::$app->request->BaseUrl; ?>/dist/js/app.min.js"></script>