controllers/GameController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Games;
use app\models\Comments;
use app\models\GameSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\filters\AccessControl;

/**
 * GameController implements the CRUD actions for Games model.
 */
class GameController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true, // Has access
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index', 'view', 'getcomment'],
                        'allow' => true, // Do not have access
                        'roles'=>['?'], // Guests '?'
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Games models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GameSearch();
        $params = Yii::$app->request->queryParams;
        if (isset($params["search_query"])){
            $searchModel->search_query = $params["search_query"];
        }
        if (isset($params["order_by"])){
            $searchModel->order_by = $params["order_by"];
        }

        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Games model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Games model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Games();
        $model->setscenario('insert');

        if ($model->load(Yii::$app->request->post())) {
            $model->AuthorId = Yii::$app->user->identity->UserId;
            $model->PostDate = new \yii\db\Expression('NOW()');

            $file1 = UploadedFile::getInstance($model, 'file');
            $model->file = $file1;

            date_default_timezone_set('Asia/Jakarta');
            
            $model->Image = 'img_'.date('dMY').'_'.date('His').'.'.$file1->extension;

                
            if ($model->save()){
                $model->file->saveAs('img/' . $model->Image); 

                return $this->redirect(['view', 'id' => $model->GameId]);   
            }else{
                return $this->render('create', [
                    'model' => $model,
                ]);    
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Games model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            date_default_timezone_set('Asia/Jakarta');

            $file1 = UploadedFile::getInstance($model, 'file');
            if ($file1 == null && $model->Image == ""){
                $model->addError('file', 'Please upload a file.');
                return $this->render('update', [
                    'model' => $model,
                ]);
            }

            if ($file1 != null){  
                $model->Image = 'img_'.date('dmY').'_'.date('His').'.'.$file1->extension;
                $model->file = $file1;
            }

            if ($model->save()){
                if ($file1 != null){
                    $model->file->saveAs('img/' . $model->Image);
                }
                return $this->redirect(['view', 'id' => $model->GameId]);   
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Games model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Games model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Games the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Games::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPostcomment()
    {
        $isAjax = isset($_SERVER['HTTP_X_REQUESTED_WITH']) AND 
            strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest';
        
        if (!$isAjax)
            throw new NotFoundHttpException('The requested page does not exist.');

        date_default_timezone_set('Asia/Jakarta');

        if (isset($_POST["game"]) && isset($_POST["comment"])){
            $model = new Comments();
            $model->GameId = $_POST["game"];
            $model->AuthorId = Yii::$app->user->identity->UserId;
            $model->Comment = $_POST["comment"];
            $model->PostDate = new \yii\db\Expression('NOW()');

            $model->save();

            $model = Comments::findOne($model->CommentId);

            return json_encode([
                'comment' => $model->Comment, 
                'id' => $model->CommentId, 
                'author' => $model->author->Firstname.' '.$model->author->Lastname, 
                'date' => $this->dateFormat($model->PostDate),
                'image' => $model->author->Image == null || $model->author->Image == "" ? 'default-pp.jpg' : $model->author->Image
            ]);
        }else{
            return [];
        }
    }

    public function actionGetcomment()
    {
        date_default_timezone_set('Asia/Jakarta');

        $isAjax = isset($_SERVER['HTTP_X_REQUESTED_WITH']) AND 
            strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest';
        
        if (!$isAjax || !isset($_GET['game']))
            throw new NotFoundHttpException('The requested page does not exist.');

        $model = new Comments();

        if (isset($_GET['id']) && $_GET['id'] > 0){
            $model = Comments::find()
                ->where('CommentId < :id', [':id' => $_GET['id']])
                ->andWhere('GameId = :game', [':game' => $_GET['game']])
                ->orderBy([ 'Postdate' => SORT_DESC ])
                ->limit(5)->all();
        }else{
            $model = Comments::find()
                ->where('GameId = :game', [':game' => $_GET['game']])
                ->orderBy([ 'Postdate' => SORT_DESC ])
                ->limit(5)
                ->all();   
        }

        $output = [];
        $minid = -1;

        foreach($model as $row){
            if ($minid == -1 || $minid > $row->CommentId){
                $minid = $row->CommentId;
            }
        }

        $comment_count = Comments::find()
            ->where('CommentId < :id', [':id' => $minid])
            ->andWhere('GameId = :game', [':game' => $_GET['game']])
            ->count();

        foreach($model as $row){
            array_push($output, [
                'comment' => $row->Comment, 
                'count' => $comment_count, 
                'id' => $row->CommentId, 
                'author' => $row->author->Firstname.' '.$row->author->Lastname, 
                'date' => $this->dateFormat($row->PostDate),
                'image' => $row->author->Image == null || $row->author->Image == "" ? 'default-pp.jpg' : $row->author->Image
            ]);
        }

        return json_encode($output);
    }

    function dateFormat($date){
        date_default_timezone_set('Asia/Jakarta');

        if (date('dmY') == date("dmY", strtotime($date))){
            return date("h:i A", strtotime($date)). ' Today';
        }else if (date('dmY') == date("dmY", strtotime('+1 day', strtotime($date)))){
            return date("h:i A", strtotime($date)). ' Yesterday';
        }else{
            return date("h:i A M d, Y", strtotime($date));
        }
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Users;
use app\models\LoginForm;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\GameSearch;
use yii\web\UploadedFile;

/**
 * UserController implements the CRUD actions for Users model.
 */
class UserController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['register'],
                        'allow' => false, // Has access
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true, // Has access
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['register'],
                        'allow' => true, // Do not have access
                        'roles'=>['?'], // Guests '?'
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionRegister()
    {
        //Yii::$app->user->identity
        $model = new Users();
        $model->setscenario('insert');

        if ($model->load(Yii::$app->request->post()) && $model->validate()) {

            date_default_timezone_set('Asia/Jakarta');

            $file1 = UploadedFile::getInstance($model, 'file');
            if ($file1 != null){  
                $model->Image = 'img_'.date('dmY').'_'.date('His').'.'.$file1->extension;
                $model->file = $file1;
            }

            $model->DateOfBirth = date("Y-m-d", strtotime($model->DateOfBirth));
            if ($model->Password != $model->varPassword){
                //reset password
                $model->Password = "";
                $model->varPassword = "";

                //set error message
                $model->addError('varPassword', 'Password confirm must be the same as password');
                $model->DateOfBirth = date("d-M-Y", strtotime($model->DateOfBirth));
                $model->file = null;

                return $this->render('register', [
                    'model' => $model,
                ]);
            }

            $model->Password = crypt($model->Password);

            if ($model->save()){

                if ($file1 != null){
                    $model->file->saveAs('img/' . $model->Image);
                }

                Yii::$app->user->login($model, 0);
                return $this->redirect(['site/index']);
                
            }else{
                $model->file = null;
                $model->DateOfBirth = date("d-M-Y", strtotime($model->DateOfBirth));
                return $this->render('register', [
                    'model' => $model,
                ]);   
            }
        } else {
            $model->file = null;
            return $this->render('register', [
                'model' => $model,
            ]);
        }
    }

    public function actionProfile()
    {
        $id = Yii::$app->user->identity->UserId;
        $model = $this->findModel($id);

        $searchModel = new GameSearch();
        $params = Yii::$app->request->queryParams;
        if (isset($params["search_query"])){
            $searchModel->search_query = $params["search_query"];
        }
        if (isset($params["order_by"])){
            $searchModel->order_by = $params["order_by"];
        }

        $searchModel->owner = $id;

        $dataProvider = $searchModel->search($params);

        return $this->render('profile', [
            'model' => $model,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Updates an existing Users model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate()
    {
        $id = Yii::$app->user->identity->UserId;
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            date_default_timezone_set('Asia/Jakarta');

            $file1 = UploadedFile::getInstance($model, 'file');
            if ($file1 != null){  
                $model->Image = 'img_'.date('dmY').'_'.date('His').'.'.$file1->extension;
                $model->file = $file1;
            }

            $model->DateOfBirth = date("Y-m-d", strtotime($model->DateOfBirth));

            if ($model->save()){
                if ($file1 != null){
                    $model->file->saveAs('img/' . $model->Image);
                }

                return $this->redirect(['profile']);   
            }else{
                $model->DateOfBirth = date("d-M-Y", strtotime($model->DateOfBirth));
                $model->file = null;
                return $this->render('update', [
                    'model' => $model,
                ]);
            }
        } else {
            $model->file = null;
            $model->DateOfBirth = date("d-M-Y", strtotime($model->DateOfBirth));
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionChangepassword()
    {
        $id = Yii::$app->user->identity->UserId;
        $model = $this->findModel($id);
        $model->setscenario('change');

        if ($model->load(Yii::$app->request->post())) {
            if (!$model->validatePassword($model->curPassword)){
                $model->curPassword = "";
                $model->varPassword = "";
                $model->newPassword = "";
                $model->addError('curPassword', 'Your current Password is incorrect');
                return $this->render('changepassword', [
                    'model' => $model,
                ]);
            }

            if ($model->newPassword != $model->varPassword){
                $model->curPassword = "";
                $model->varPassword = "";
                $model->newPassword = "";
                $model->addError('varPassword', 'Password confirm must be the same as new password');
                return $this->render('changepassword', [
                    'model' => $model,
                ]);
            }

            $model->Password = crypt($model->newPassword);

            if ($model->save()){
                return $this->redirect(['profile']);
            }

        } else {
            return $this->render('changepassword', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Finds the Users model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Users the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\datecontrol\Module;
use kartik\datecontrol\DateControl;
use kartik\date\DatePicker;

/* @var $this yii\web\View */
/* @var $model app\models\Users */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="users-form">

    <?php $form = ActiveForm::begin(['options'=>['class'=>'form-horizontal', 'enctype' => 'multipart/form-data']]); ?>

    <div class="box-body">

    <?php 
        if ($model->isNewRecord){
            echo $form->field($model, 'Email', [
                'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
                'labelOptions'=>['class'=>'col-sm-2 control-label'],
            ])->textInput(['maxlength' => true]);
        }else{
            echo '<div class="form-group">';
            echo Html::activeLabel($model, 'Email', ['class'=>'col-sm-2 control-label']);
            echo '<div class="col-sm-10" style="margin-bottom:10px"><span class="form-control">'.$model->Email.'</span></div></div>';
            
        }
    ?>

    <?php
    
        if ($model->isNewRecord){
            echo $form->field($model, 'Username', [
                'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
                'labelOptions'=>['class'=>'col-sm-2 control-label']
            ])->textInput(['maxlength' => true]);
        }else{
            echo '<div class="form-group">';
            echo Html::activeLabel($model, 'Username', ['class'=>'col-sm-2 control-label']);
            echo '<div class="col-sm-10" style="margin-bottom:10px"><span class="form-control">'.$model->Username.'</span></div></div>';
            
        }
    

    ?>

    <?= $form->field($model, 'Firstname', [
        'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
        'labelOptions'=>['class'=>'col-sm-2 control-label']
    ])->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Lastname', [
        'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
        'labelOptions'=>['class'=>'col-sm-2 control-label']
    ])->textInput(['maxlength' => true]) ?>

    <?php
        if ($model->isNewRecord){
            echo $form->field($model, 'Password', [
                'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
                'labelOptions'=>['class'=>'col-sm-2 control-label']
            ])->passwordInput(['maxlength' => true]);
            echo $form->field($model, 'varPassword', [
                'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
                'labelOptions'=>['class'=>'col-sm-2 control-label']
            ])->passwordInput(['maxlength' => true]);
        }
    ?>

    <?php
        echo $form->field($model, 'DateOfBirth', [
            'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
            'labelOptions'=>['class'=>'col-sm-2 control-label']
        ])->widget(
            DatePicker::classname(), [
                'options' => ['placeholder' => 'Enter date of birth..'],
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'd-M-yyyy'
                ]
            ]
        );
    ?>

    <?= $form->field($model, 'file', [
            'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
            'labelOptions'=>['class'=>'col-sm-2 control-label'],
            'inputOptions'=>['style'=>'margin-top:5px']
        ])->fileInput() ?> 

    </div>

    <div class="box-footer">
        <?= Html::submitButton($model->isNewRecord ? 'Register' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success pull-right' : 'btn btn-primary pull-right']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

<style>
    .form-horizontal .form-group{
        margin-bottom:5px;
    }
</style>

views/user/changepassword.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Change Password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-register">
<div class="box box-default">
	<?php $form = ActiveForm::begin(['options'=>['class'=>'form-horizontal', 'enctype' => 'multipart/form-data']]); ?>
	
	<div class="box-body">	
    	<?php
    		
    		echo $form->field($model, 'curPassword', [
                'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
                'labelOptions'=>['class'=>'col-sm-2 control-label']
            ])->passwordInput(['maxlength' => true]);
    		echo $form->field($model, 'newPassword', [
                'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
                'labelOptions'=>['class'=>'col-sm-2 control-label']
            ])->passwordInput(['maxlength' => true]);
            echo $form->field($model, 'varPassword', [
                'template' => '{label}<div class="col-sm-10">{input}{error}{hint}</div>',
                'labelOptions'=>['class'=>'col-sm-2 control-label']
            ])->passwordInput(['maxlength' => true]);

    	?>

		<div class="box-footer">
	        <?= Html::submitButton($model->isNewRecord ? 'Register' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success pull-right' : 'btn btn-primary pull-right']) ?>
	    </div>

    </div>

    <?php ActiveForm::end(); ?>
</div>

</div>

views/user/profile.php
<?php

use yii\helpers\Html;
use yii\widgets\ListView;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'My Pages';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-register">
	
<div class="box-body">
<div class="row">
            <div class="col-md-3">

              <!-- Profile Image -->
              <div class="box box-primary">
                <div class="box-tools pull-right">
					<?= Html::a('<i class="fa fa-pencil"></i>', ['update'], [
					    'class' => 'btn btn-box-tool',
					    'data-toggle'=>'tooltip',
					    'title'=>'Edit',
					]) ?>
				</div>
                <div class="box-body box-profile">
                  <img class="profile-user-img img-responsive img-circle" src="<?= \Yii::$app->request->BaseUrl; ?>/img/<?= Yii::$app->user->identity->Image == null || Yii::$app->user->identity->Image == "" ? 'default-pp.jpg' : Yii::$app->user->identity->Image ?>" alt="User profile picture">
                  <h3 class="profile-username text-center"><?= $model->Firstname . ' ' . $model->Lastname ?></h3>
                  <p class="text-muted text-center"><?= $model->Email ?></p>

                  <ul class="list-group list-group-unbordered">
                  	<li class="list-group-item">
                      <b>Games</b> <a class="pull-right"><?= count($model->games) ?></a>
                    </li>
                    <li class="list-group-item">
                      <b>Comments</b> <a class="pull-right"><?= count($model->comments) ?></a>
                    </li>
                  </ul>
                </div><!-- /.box-body -->
              </div><!-- /.box -->

              <!-- About Me Box -->
              <div class="box box-primary">
                <div class="box-header with-border">
                  <h3 class="box-title">About Me</h3>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <strong><i class="fa fa-birthday-cake margin-r-5"></i>  Born</strong>
                  <p class="text-muted">
                    <?= date("F d, Y", strtotime($model->DateOfBirth)) ?>
                  </p>

                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
            <div class="col-md-9">
              
              <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                  <li class="active"><a href="#activity" data-toggle="tab">Activity</a></li>
                </ul>
                <div class="tab-content">
                  <div class="active tab-pane" id="activity">
                    <!-- Post -->
                    <div class="post">
                      <div class="box-header">
      <div class="box-tools">
<?= Html::beginForm('profile', 'GET', ['id'=>'form-search']) ?>

    <div class="input-group" style="width: 350px;">

            <?php 
                echo Html::activeTextInput($searchModel, 'search_query', [
                        'maxlength' => 150, 'placeholder'=>'Search',
                        'class'=>'form-control input-sm pull-right',
                        'style'=>'width:160px',
                        'name'=>'search_query'
                ]); 
            ?>

            <div class="input-group-btn">
                <button class="btn btn-sm btn-default" style="z-index: 2;margin-left: -1px;border-top-left-radius: 0;
                    border-bottom-left-radius: 0;"><i class="fa fa-search"></i></button>
            </div>

            <?php 
                echo Html::activeDropDownList($searchModel, 'order_by', 
                [ 'na'=>'Name (a - z)', 'nd'=>'Name (z - a)', 'dd'=>'Date (newest - oldest)', 'da'=>'Date (oldest - newest)' ],
                [
                    'class'=>'form-control input-sm', 'style'=>'margin-left:5px;',
                    'id'=>'sort_option', 'name'=>'order_by'
                ]); 
            ?>
    
        </div>
<?= Html::endForm() ?>
      </div>
    </div>

    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemOptions' => ['class' => 'item'],
        'itemView' => function ($model, $key, $index, $widget) {
                //return Html::a(Html::encode($model->Name), ['view', 'id' => $model->GameId]);
                $str = $model->Description;
                if (strlen($model->Description) > 260){
                    $str = substr($str, 0, 257) . '...';   
                }
                return '<div class="attachment-block clearfix">
                            <img class="attachment-img" src="'.\Yii::$app->request->BaseUrl.'/img/'.$model->Image.'" alt="attachment image">
                            <div class="attachment-pushed">
                              <h4 class="attachment-heading">'.Html::a(Html::encode($model->Name), ['game/view', 'id' => $model->GameId]).'</h4>
                              <div class="attachment-text attachment-body">'.$str.'</div>
                              <div class="attachment-text pull-right">
                                    <i>'.$model->author->Firstname.' '.$model->author->Lastname.', '.date("M d, Y H:i", strtotime($model->PostDate)).'</i>
                              </div>
                            </div>
                          </div>';
            },
    ]) ?>
                    </div><!-- /.post -->
                  </div><!-- /.tab-pane -->
                </div><!-- /.tab-content -->
              </div><!-- /.nav-tabs-custom -->
            </div><!-- /.col -->
          </div>
</div>

</div>

<?php    

$this->registerJs('
    $( document ).ready(function() {
        $("#sort_option").change(function (e){
            $("#form-search").submit();
        });

        var search = $("#gamesearch-search_query").val();
        if (search.trim() != ""){
            $(".attachment-heading a").each(function (index, item){
                var innerText = $(item).text();
                $(item).text("").append(highlight(innerText, search));
            });

            $(".attachment-body").each(function (index, item){
                var innerText = $(item).text();
                $(item).text("").append(highlight(innerText, search));
            });
        }

        
    });

    function highlight(html, search){
        if (html.toLowerCase().indexOf(search.toLowerCase()) >= 0)
            html = html.replace(new RegExp( "(" + search + ")", "gi" ), "<mark>$1</mark>" )
        else
            html = html.replace("...","<mark>...</mark>");

        return html;
    }
')

?>

<style>
    .attachment-text, .attachment-footer{
        font-size:11px;
    }
</style>

views/user/register.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Register User';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="users-register">
<div class="box box-default">
	<div class="box-body">
	
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

    </div>
</div>

</div>

views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Users */

$this->title = 'Update User Profile';
$this->params['breadcrumbs'][] = ['label' => 'My Pages', 'url' => ['profile']];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="users-update">
<div class="box box-default">
<div class="box-body">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>
</div>
</div>