models/Games.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "games".
 *
 * @property integer $GameId
 * @property string $Name
 * @property string $Description
 * @property string $Image
 * @property integer $AuthorId
 * @property string $PostDate
 * @property string $Review
 *
 * @property Comments[] $comments
 * @property Users $author
 */
class Games extends \yii\db\ActiveRecord
{
    public $file;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'games';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['Name', 'Description', 'Image', 'AuthorId', 'PostDate', 'Review'], 'required'],
            [['Description'], 'string'],
            [['AuthorId'], 'integer'],
            [['PostDate'], 'safe'],
            [['Name'], 'string', 'max' => 150],
            [['Image'], 'string', 'max' => 500],
            [['Review'], 'string', 'max' => 500],
            [['file'],'safe'],
            [['file'], 'file', 'skipOnEmpty' => false, 'on' => 'insert'],
            [['AuthorId'], 'exist', 'skipOnError' => true, 'targetClass' => Users::className(), 'targetAttribute' => ['AuthorId' => 'UserId']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'GameId' => 'Game ID',
            'Name' => 'Name',
            'Description' => 'Description',
            'Image' => 'Image',
            'file' => 'Image',
            'AuthorId' => 'Author ID',
            'PostDate' => 'Post Date',
            'Review' => 'Review',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comments::className(), ['GameId' => 'GameId']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Users::className(), ['UserId' => 'AuthorId']);
    }
}

controllers/GameController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Games;
use app\models\Comments;
use app\models\GameSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\UploadedFile;
use yii\helpers\FileHelper;
use yii\filters\AccessControl;

/**
 * GameController implements the CRUD actions for Games model.
 */
class GameController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true, // Has access
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index', 'view', 'getcomment'],
                        'allow' => true, // Do not have access
                        'roles'=>['?'], // Guests '?'
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Games models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new GameSearch();
        $params = Yii::$app->request->queryParams;
        if (isset($params["search_query"])){
            $searchModel->search_query = $params["search_query"];
        }
        if (isset($params["order_by"])){
            $searchModel->order_by = $params["order_by"];
        }

        $dataProvider = $searchModel->search($params);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Games model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Games model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Games();
        $model->setscenario('insert');

        if ($model->load(Yii::$app->request->post())) {
            $model->AuthorId = Yii::$app->user->identity->UserId;
            $model->PostDate = new \yii\db\Expression('NOW()');

            $file1 = UploadedFile::getInstance($model, 'file');
            $model->file = $file1;

            date_default_timezone_set('Asia/Jakarta');
            
            $model->Image = 'img_'.date('dMY').'_'.date('His').'.'.$file1->extension;

                
            if ($model->save()){
                $model->file->saveAs('img/' . $model->Image); 

                return $this->redirect(['view', 'id' => $model->GameId]);   
            }else{
                return $this->render('create', [
                    'model' => $model,
                ]);    
            }
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Games model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            date_default_timezone_set('Asia/Jakarta');

            $file1 = UploadedFile::getInstance($model, 'file');
            if ($file1 == null && $model->Image == ""){
                $model->addError('file', 'Please upload a file.');
                return $this->render('update', [
                    'model' => $model,
                ]);
            }

            if ($file1 != null){  
                $model->Image = 'img_'.date('dmY').'_'.date('His').'.'.$file1->extension;
                $model->file = $file1;
            }

            if ($model->save()){
                if ($file1 != null){
                    $model->file->saveAs('img/' . $model->Image);
                }
                return $this->redirect(['view', 'id' => $model->GameId]);   
            }
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Games model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Games model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Games the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Games::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionPostcomment()
    {
        $isAjax = isset($_SERVER['HTTP_X_REQUESTED_WITH']) AND 
            strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest';
        
        if (!$isAjax)
            throw new NotFoundHttpException('The requested page does not exist.');

        date_default_timezone_set('Asia/Jakarta');

        if (isset($_POST["game"]) && isset($_POST["comment"])){
            $model = new Comments();
            $model->GameId = $_POST["game"];
            $model->AuthorId = Yii::$app->user->identity->UserId;
            $model->Comment = $_POST["comment"];
            $model->PostDate = new \yii\db\Expression('NOW()');

            $model->save();

            $model = Comments::findOne($model->CommentId);

            return json_encode([
                'comment' => $model->Comment, 
                'id' => $model->CommentId, 
                'author' => $model->author->Firstname.' '.$model->author->Lastname, 
                'date' => $this->dateFormat($model->PostDate),
                'image' => $model->author->Image == null || $model->author->Image == "" ? 'default-pp.jpg' : $model->author->Image
            ]);
        }else{
            return [];
        }
    }

    public function actionGetcomment()
    {
        date_default_timezone_set('Asia/Jakarta');

        $isAjax = isset($_SERVER['HTTP_X_REQUESTED_WITH']) AND 
            strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) === 'xmlhttprequest';
        
        if (!$isAjax || !isset($_GET['game']))
            throw new NotFoundHttpException('The requested page does not exist.');

        $model = new Comments();

        if (isset($_GET['id']) && $_GET['id'] > 0){
            $model = Comments::find()
                ->where('CommentId < :id', [':id' => $_GET['id']])
                ->andWhere('GameId = :game', [':game' => $_GET['game']])
                ->orderBy([ 'Postdate' => SORT_DESC ])
                ->limit(5)->all();
        }else{
            $model = Comments::find()
                ->where('GameId = :game', [':game' => $_GET['game']])
                ->orderBy([ 'Postdate' => SORT_DESC ])
                ->limit(5)
                ->all();   
        }

        $output = [];
        $minid = -1;

        foreach($model as $row){
            if ($minid == -1 || $minid > $row->CommentId){
                $minid = $row->CommentId;
            }
        }

        $comment_count = Comments::find()
            ->where('CommentId < :id', [':id' => $minid])
            ->andWhere('GameId = :game', [':game' => $_GET['game']])
            ->count();

        foreach($model as $row){
            array_push($output, [
                'comment' => $row->Comment, 
                'count' => $comment_count, 
                'id' => $row->CommentId, 
                'author' => $row->author->Firstname.' '.$row->author->Lastname, 
                'date' => $this->dateFormat($row->PostDate),
                'image' => $row->author->Image == null || $row->author->Image == "" ? 'default-pp.jpg' : $row->author->Image
            ]);
        }

        return json_encode($output);
    }

    function dateFormat($date){
        date_default_timezone_set('Asia/Jakarta');

        if (date('dmY') == date("dmY", strtotime($date))){
            return date("h:i A", strtotime($date)). ' Today';
        }else if (date('dmY') == date("dmY", strtotime('+1 day', strtotime($date)))){
            return date("h:i A", strtotime($date)). ' Yesterday';
        }else{
            return date("h:i A M d, Y", strtotime($date));
        }
    }
}

views/game/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Games */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="games-form">

<div class="box-body">
    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <?= $form->field($model, 'Name')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'Description')->textarea(['rows' => 12]) ?>

    <?= $form->field($model, 'Review')->textarea(['rows' => 6, 'maxlength' => true]) ?>

    <?= $form->field($model, 'file')->fileInput() ?> 

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>
</div>

</div>

views/game/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = 'Create Games';
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="games-create">
<div class="box box-default">

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>
</div>

views/game/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ActiveForm;
use yii\widgets\ListView;
use yii\helpers\BaseHtml;
/* @var $this yii\web\View */
/* @var $searchModel app\models\GameSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Games';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="games-index">

<div class="box box-default">

<div class="box-body">

    <div class="box-header">
      <div class="box-tools">
<?= Html::beginForm('index', 'GET', ['id'=>'form-search']) ?>
    <div class="input-group" style="width: 350px;">

            <?php 
                echo Html::activeTextInput($searchModel, 'search_query', [
                        'maxlength' => 150, 'placeholder'=>'Search',
                        'class'=>'form-control input-sm pull-right',
                        'style'=>'width:160px',
                        'name'=>'search_query'
                ]); 
            ?>

            <div class="input-group-btn">
                <button class="btn btn-sm btn-default" style="z-index: 2;margin-left: -1px;border-top-left-radius: 0;
                    border-bottom-left-radius: 0;"><i class="fa fa-search"></i></button>
            </div>

            <?php 
                echo Html::activeDropDownList($searchModel, 'order_by', 
                [ 'na'=>'Name (a - z)', 'nd'=>'Name (z - a)', 'dd'=>'Date (newest - oldest)', 'da'=>'Date (oldest - newest)' ],
                [
                    'class'=>'form-control input-sm', 'style'=>'margin-left:5px;',
                    'id'=>'sort_option', 'name'=>'order_by'
                ]); 
            ?>
    
        </div>
<?= Html::endForm() ?>
      </div>
    </div>

    <?= ListView::widget([
        'dataProvider' => $dataProvider,
        'itemOptions' => ['class' => 'item'],
        'itemView' => function ($model, $key, $index, $widget) {
                //return Html::a(Html::encode($model->Name), ['view', 'id' => $model->GameId]);
                $str = $model->Description;
                if (strlen($model->Description) > 380){
                    $str = substr($str, 0, 377) . '...';   
                }
                return '<div class="attachment-block clearfix">
                            <img class="attachment-img" src="'.\Yii::$app->request->BaseUrl.'/img/'.$model->Image.'" alt="attachment image">
                            <div class="attachment-pushed">
                              <h4 class="attachment-heading">'.Html::a(Html::encode($model->Name), ['view', 'id' => $model->GameId]).'</h4>
                              <div class="attachment-text attachment-body">'.$str.'</div>
                              <div class="attachment-text pull-right">
                                    <i>'.$model->author->Firstname.' '.$model->author->Lastname.', '.date("M d, Y H:i", strtotime($model->PostDate)).'</i>
                              </div>
                            </div>
                          </div>';
            },
    ]) ?>

</div>

</div>

</div>

<style>
    .attachment-text, .attachment-footer{
        font-size:11px;
    }
</style>


<?php    

$this->registerJs('
    $( document ).ready(function() {
        $("#sort_option").change(function (e){
            $("#form-search").submit();
        });

        var search = $("#gamesearch-search_query").val();
        if (search.trim() != ""){
            $(".attachment-heading a").each(function (index, item){
                var innerText = $(item).text();
                $(item).text("").append(highlight(innerText, search));
            });

            $(".attachment-body").each(function (index, item){
                var innerText = $(item).text();
                $(item).text("").append(highlight(innerText, search));
            });
        }

        
    });

    function highlight(html, search){
        if (html.toLowerCase().indexOf(search.toLowerCase()) >= 0)
            html = html.replace(new RegExp( "(" + search + ")", "gi" ), "<mark>$1</mark>" )
        else
            html = html.replace("...","<mark>...</mark>");

        return html;
    }
')

?>

views/game/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = 'Update Games';
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->Name, 'url' => ['view', 'id' => $model->GameId]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="games-update">
<div class="box box-default">
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>
</div>
</div>

views/game/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Games */

$this->title = 'Game Review';
$this->params['breadcrumbs'][] = ['label' => 'Games', 'url' => ['index']];
$this->params['breadcrumbs'][] = $model->Name;
?>
<div class="games-view">

<div class="box box-default">

    <div class="box box-widget" style="margin-top:1px">
            
            <div class="box box-widget widget-user" style="margin-bottom:0px">
                <!-- Add the bg color to the header using any of the bg-* classes -->
                <div class="widget-user-header bg-black" style="background: linear-gradient( rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3) ), 
                url('<?= \Yii::$app->request->BaseUrl; ?>/img/<?= $model->Image ?>') center center; height:350px;background-size: cover;
                background-position-y: -50px;">

                    <h1 style="text-align: center;"><?= $model->Name ?></h1>
                    <h5 style="text-align: center;"><?= nl2br($model->Review) ?></h5>
                </div>

                

              </div>
              
                <div class="box-header with-border">
                  <div class="user-block">
                    <img class="img-circle" src="<?= \Yii::$app->request->BaseUrl; ?>/img/<?= $model->author->Image == null || $model->author->Image == "" ? 'default-pp.jpg' : $model->author->Image ?>" alt="user image">
                    <span class="username"><a href="#"><?= $model->author->Firstname . ' ' . $model->author->Lastname ?></a></span>
                    <span class="description"><?= date("M d, Y H:i", strtotime($model->PostDate)) ?></span>
                  </div><!-- /.user-block -->
<?php if (isset(Yii::$app->user->identity->Username) && $model->AuthorId == Yii::$app->user->identity->UserId){ ?>
                  <div class="box-tools pull-right">
<?= Html::a('<i class="fa fa-pencil"></i>', ['update', 'id' => $model->GameId], [
    'class' => 'btn btn-box-tool',
    'data-toggle'=>'tooltip',
    'title'=>'Edit'
]) ?>
<?= Html::a('<i class="fa fa-trash"></i>', ['delete', 'id' => $model->GameId], [
    'class' => 'btn btn-box-tool',
    'data-toggle'=>'tooltip',
    'title'=>'Delete',
    'data' => [
        'confirm' => 'Are you sure you want to delete this item?',
        'method' => 'post',
    ],
]) ?>
                  </div>
<?php } ?>
                </div><!-- /.box-header -->
                <div class="box-body">
                  <!-- post text -->
                  <p><?= nl2br($model->Description) ?></p>
                  <span class="pull-right text-muted" style="margin-right:5px;display:none" id="span-more-comment">
                    <a href="#" id="more-comment">View <span id="comment-count"></span> more comments</a></span>
                </div><!-- /.box-body -->
                <div class="box-footer box-comments" id="comments">
                    <span id="comment-note">Be the first to comment...</span>
                </div><!-- /.box-footer -->
                <?php if (isset(Yii::$app->user->identity->Username)){ ?>
                <div class="box-footer">
                  <form id="form-comment">
                    <img class="img-responsive img-circle img-sm" src="<?= \Yii::$app->request->BaseUrl; ?>/img/<?= Yii::$app->user->identity->Image == null || Yii::$app->user->identity->Image == "" ? 'default-pp.jpg' : Yii::$app->user->identity->Image ?>" alt="alt text">
                    <!-- .img-push is used to add margin to elements next to floating images -->
                    <div class="img-push">
                      <input id="CommentInput" type="text" class="form-control input-sm" placeholder="Press enter to post comment">
                    </div>
                  </form>
                </div><!-- /.box-footer -->
                <?php } ?>
              </div>

</div>
</div>
<?php

$this->registerJs('
    function handleSubmit() {
        var data = {
            "comment": $("#CommentInput").val(),
            "game": '.$model->GameId.',
        };

        postComment(data);

        return false;
    }

    function postComment(data) {
        $.ajax({
            type: "POST",
            url: "'.yii\helpers\Url::toRoute('game/postcomment').'",
            data: data,
            headers: {
              "X-Requested-With": "XMLHttpRequest"
            },
            success: postSuccess,
            error: postError
        });
    }

    function postError(jqXHR, textStatus, errorThrown){
        console.log(jqXHR);
        alert("An error occurred while posting your comment. Please try again later.");
    }

    function postSuccess(data, textStatus, jqXHR) {
        if (data == ""){
            alert("An error occurred while posting your comment. Please try again later.");
            return;
        }

        $("#form-comment").get(0).reset();
        $("#comment-note").remove();

        data = JSON.parse(data);

        var html = commentHtml(data);
        $("#comments").append($(html).fadeIn("normal"));
    }

    function loadComment(id){
        id = id || 0;
        $.ajax({
            type: "GET",
            url: "'.yii\helpers\Url::toRoute('game/getcomment').'",
            data: {"id":id,"game":'.$model->GameId.'},
            headers: {
              "X-Requested-With": "XMLHttpRequest"
            },
            success: getSuccess,
            error: getError
        });
    }

    function getError(jqXHR, textStatus, errorThrown){
        alert("An error occurred while loading comments. Please try again later.");
    }

    function getSuccess(data, textStatus, jqXHR){
        data = JSON.parse(data);

        if (data.length < 1){
            $("#span-more-comment").hide();
            return;
        }
        
        $("#comment-note").remove();
        $("#comment-count").text(data[0].count);
        if (data[0].count == 0){
            $("#span-more-comment").hide();
        }else{
            $("#span-more-comment").show();
        }

        for(var i = 0; i < data.length; i++){    
            if ($(\'input.asdklfjwiersdfb[value="\'+data[i].id+\'"]\').length == 0){
                var html = commentHtml(data[i]);
                $("#comments").prepend($(html).fadeIn("normal"));   
            }
        }
    }

    function commentHtml(data){
        var html = \'\'+
            \'<div class="box-comment">\'+
                \'<input type="hidden" class="asdklfjwiersdfb" value="\'+data.id+\'"/>\'+
                \'<img class="img-circle img-sm" src="'.\Yii::$app->request->BaseUrl.'/img/\'+data.image+\'" alt="user image">\'+
                \'<div class="comment-text">\'+
                    \'<span class="username">\'+
                        data.author+
                        \'<span class="text-muted pull-right">\'+data.date+\'</span>\'+
                    \'</span>\'+ data.comment +
                \'</div>\'+
            \'</div>\';

        return html;
    }

    $( document ).ready(function() {
        $("#form-comment").submit(handleSubmit);

        loadComment();

        $("#more-comment").click(function(e){
            var lastid = $("input.asdklfjwiersdfb").clone().sort(function(a, b) {
                return parseInt($(a).attr("value")) - parseInt($(b).attr("value"));
            }).first().attr("value");

            loadComment(lastid);

            return false;
        });
    });

    

');

?>
<style>
    #more-comment:hover{
        text-decoration: underline;
    }
</style>